# Generated by Django 5.1.4 on 2026-07-31 18:43

import django.db.models.deletion
import skin.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('concern', models.JSONField(default=list)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=skin.models.orignial_image_upload_path)),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to=skin.models.resized_image_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('skin_concern', models.CharField(max_length=100)),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to=skin.models.mask_image_upload_path)),
                ('ui_score', models.FloatField(blank=True, null=True)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to=skin.models.overlay_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='skin.scan')),
            ],
        ),
    ]
