# Generated by Django 5.1.4 on 2026-08-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0002_scan_scanresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='concern',
            new_name='selected_concern',
        ),
    ]
