# Generated by Django 5.1.4 on 2026-08-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0003_rename_concern_scan_selected_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='skin_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='skin_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
