# Generated by Django 5.1.4 on 2026-08-02 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0004_scan_overall_score_scan_skin_age_scan_skin_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('skin_goals', models.JSONField(blank=True, default=list, null=True)),
                ('budget', models.CharField(blank=True, choices=[('budget', 'Budget'), ('mid', 'Mid Range'), ('premium', 'Premium')], max_length=10, null=True)),
                ('allergies', models.JSONField(blank=True, default=list, null=True)),
                ('pregnancy_status', models.BooleanField(blank=True, null=True)),
                ('vegan_cruelty_free', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin.skinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('ingredients', models.JSONField(blank=True, default=list, null=True)),
                ('usage_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, null=True)),
                ('side_effects', models.JSONField(blank=True, default=list, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skin.skinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True)),
                ('smoking', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly')], max_length=50, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('Never', 'Never'), ('Occasionally', 'Occasionally'), ('Regularly', 'Regularly')], max_length=50, null=True)),
                ('exercise_frequency', models.CharField(blank=True, choices=[('None', 'None'), ('1-2/week', '1-2 times/week'), ('3-5/week', '3-5 times/week'), ('Daily', 'Daily')], max_length=50, null=True)),
                ('exercise_hours_per_week', models.FloatField(blank=True, null=True)),
                ('sun_exposure', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50, null=True)),
                ('spf_usage', models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Always', 'Always')], max_length=50, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skin.skinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Detailed_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.JSONField(blank=True, default=list, null=True)),
                ('baseline_skin_types', models.JSONField(blank=True, default=list, null=True)),
                ('diet_environment_factors', models.JSONField(blank=True, default=list, null=True)),
                ('skin_concern_history', models.JSONField(blank=True, default=list, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skin.skinprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_routine', models.JSONField(blank=True, default=list, null=True)),
                ('night_routine', models.JSONField(blank=True, default=list, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skin.skinprofile')),
            ],
        ),
    ]
